
netflix_Proj:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      schema: raw
      threads: 10
      type: postgres
      user: "{{ env_var('DB_USERNAME') }}"
  target: dev
