
netflix_Proj:
  outputs:
    dev:
      dbname: netflix
      host: ep-cool-surf-abds13vc-pooler.eu-west-2.aws.neon.tech
      pass: npg_p5mJ3qEGDBvX
      port: 5432
      schema: raw
      threads: 10
      type: postgres
      user: neondb_owner
  target: dev
