version: 2

sources:
  - name: raw                 # The first part of source('raw', 'NetflixData')
    schema: raw               # Actual schema in your DB (change if needed, e.g., public)
    tables:
      - name: stg_netflix     # The second part of source('raw', 'NetflixData')
        description: "This is the raw Netflix data source containing information about Netflix content."
        
models:
  - name: int_netflix
    description: "This model transforms some of the columns so that there are no null rows."
    columns:
      - name: id
        description: "TEST"
        data_tests:
          - unique
          - not_null
      - name: Category
        description: "The category of the Netflix content, for example, Movie or TV Show"  
        data_tests:
          - not_null
      - name: Title
        description: "The title of the Netflix content"
      - name: Director
        description: "The director(s) of the Netflix content"
      - name: Cast 
        description: "A list of actors who appeared in the Netflix content"
      - name: Country
        description: "The country where the Netflix content was produced"
      - name: release_date
        description: "The release date of the Netflix content"
      - name: rating
        description: "TEST"
      - name: duration_min
        description: "The duration of the Netflix content, applicable for movies"
      - name: duration_season
        description: "The number of seasons for TV shows"